In [38]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [39]:
data = pd.read_csv("./data/MNIST/mnist_train.csv")
data = np.array(data)

In [40]:
np.random.shuffle(data)

data_test = data[0:1000].T
X_test = data_test[1:]
Y_test = data_test[0]

data_train = data[1000:].T
X_train = data_train[1:]
Y_train = data_train[0]

m = len(data)

In [41]:
def init_variables():
    W1 = np.random.random((10, 784)) - 0.5
    b1 = np.random.random((10, 1)) - 0.5
    W2 = np.random.random((10, 10)) - 0.5
    b2 = np.random.random((10, 1)) - 0.5
    return W1, b1, W2, b2


In [42]:
def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z)/ np.sum(np.exp(Z))

def forward_prop(X, W1, b1, W2, b2):
    A0 = X

    Z1 = W1.dot(A0) + b1
    A1 = ReLU(Z1)
    
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    
    return A0, Z1, A1, Z2, A2

In [43]:
def hot_not(Y):
    hot_not_Y = np.zeros((10, len(Y)))
    for i in range(len(Y)):
        hot_not_Y[Y[i]][i] = 1
    return hot_not_Y

def deriv_ReLU(Z):
    return Z >= 0

def backward_prop(X, Y, A0, Z1, A1, Z2, A2, W1, b1, W2, b2):
    dZ2 = A2 - hot_not(Y)
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    
    dZ1 = (W2.T).dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)

    return dW1, db1, dW2, db2

In [44]:
def update_variables(alpha, W1, b1, W2, b2, dW1, db1, dW2, db2):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2

In [45]:
def get_prediction(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.sum()

def train_model(X, Y, iterations, alpha):
    for i in range(iterations):
        W1, b1, W2, b2 = init_variables()
        A0, Z1, A1, Z2, A2 = forward_prop(X, W1, b1, W2, b2)
        dW1, db1, dW2, db2 = backward_prop(X, Y, A0, Z1, A1, Z2, A2, W1, b1, W2, b2)
        update_variables(alpha, W1, b1, W2, b2, dW1, db1, dW2, db2)
        if i % 10 == 0:
            print(f"Iteration {i} is done. Current accuracy is {get_accuracy(get_prediction(A2), Y)}")
    print("Training is done.")
    return A2

guessed_array = train_model(X_train, Y_train, 30, 0.1)
        

C:\Users\amine\AppData\Local\Temp\ipykernel_36256\975632568.py:5: RuntimeWarning: overflow encountered in exp
  return np.exp(Z)/ np.sum(np.exp(Z))
d:\Projects\DS&ML\neural_network_from_scratch\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\amine\AppData\Local\Temp\ipykernel_36256\975632568.py:5: RuntimeWarning: invalid value encountered in divide
  return np.exp(Z)/ np.sum(np.exp(Z))


[0 0 0 ... 0 0 0] [8 0 7 ... 5 4 6]
Iteration 0 is done. Current accuracy is 0.017812566592590336
[0 0 0 ... 7 0 0] [8 0 7 ... 5 4 6]
Iteration 10 is done. Current accuracy is 0.021515114615361198
[4 0 0 ... 4 4 1] [8 0 7 ... 5 4 6]
Iteration 20 is done. Current accuracy is 0.02074644585832141
Training is done.


In [46]:
import plot_utils
plot_utils.plot_number(guessed_array[5], Y_train[5])

AttributeError: module 'plot_utils' has no attribute 'plot_number'